import { useCallback, useEffect, useState } from 'react';
import * as DocumentPicker from 'expo-document-picker';
import { StatusBar } from 'expo-status-bar';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { ActivityIndicator, Alert, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, Share, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { api, jsonBody, login, logout, restoreSession, type AdminUser, type ForecastRun, type ImportRecord, type NotificationSettings, type Overview, type Product, type ReportRecord, type Series, type SettingsData, type User } from './src/api';

const c = { bg: '#0e1422', card: '#192234', raised: '#222d42', line: '#304056', text: '#f3f8ff', muted: '#a7b4c9', blue: '#3e7bfa', cyan: '#1fd4c0', red: '#fb6674', amber: '#ffc06b' };
type Tab = 'Home' | 'Products' | 'Forecast' | 'Upload' | 'More';
type Screen = Tab | 'Reports' | 'Insights' | 'Profile' | 'Settings' | 'Notifications' | 'Admin';
const tabs: Tab[] = ['Home', 'Products', 'Forecast', 'Upload', 'More'];
const periods = [30, 90, 180, 365] as const;
const number = (value: number) => Number(value || 0).toLocaleString();
const money = (value: number, currency: string) => `${currency === 'PKR' ? 'Rs' : `${currency} `}${number(Math.round(value))}`;
const message = (error: unknown) => error instanceof Error ? error.message : 'Please try again.';

function Button({ title, onPress, secondary = false, danger = false, disabled = false, compact = false }: { title: string; onPress: () => void; secondary?: boolean; danger?: boolean; disabled?: boolean; compact?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button, secondary && s.secondary, danger && s.dangerButton, compact && s.compactButton, disabled && { opacity: 0.6 }]}><Text style={s.buttonText}>{title}</Text></Pressable>;
}
function Card({ children }: { children: React.ReactNode }) { return <View style={s.card}>{children}</View>; }
function Field({ label, value, onChangeText, secure = false, numeric = false }: { label: string; value: string; onChangeText: (value: string) => void; secure?: boolean; numeric?: boolean }) {
  return <View><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} secureTextEntry={secure} keyboardType={numeric ? 'numeric' : label.toLowerCase().includes('email') ? 'email-address' : 'default'} autoCapitalize={label.toLowerCase().includes('email') ? 'none' : 'sentences'} autoCorrect={false} placeholderTextColor={c.muted} style={s.input} /></View>;
}
function ErrorText({ text }: { text: string }) { return text ? <Text style={s.error}>{text}</Text> : null; }
function Page({ title, subtitle, back, children }: { title: string; subtitle?: string; back?: () => void; children: React.ReactNode }) {
  return <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">{back ? <Pressable onPress={back}><Text style={s.back}>‹ More</Text></Pressable> : null}<Text style={s.title}>{title}</Text>{subtitle ? <Text style={s.muted}>{subtitle}</Text> : null}{children}</ScrollView>;
}
function Chips<T extends string | number>({ values, selected, onSelect, format }: { values: readonly T[]; selected: T; onSelect: (value: T) => void; format?: (value: T) => string }) {
  return <ScrollView horizontal showsHorizontalScrollIndicator={false}>{values.map(value => <Pressable key={String(value)} onPress={() => onSelect(value)} style={[s.chip, value === selected && s.chipActive]}><Text style={s.strong}>{format ? format(value) : String(value)}</Text></Pressable>)}</ScrollView>;
}

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit() { if (!email.trim() || !password) return setError('Enter your email and password.'); setBusy(true); setError(''); try { onLogin(await login(email.trim(), password)); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={s.login} keyboardShouldPersistTaps="handled"><Image source={require('./assets/stockguard-logo.png')} style={s.logo} resizeMode="contain" accessibilityLabel="StockGuard AI logo" /><Text style={s.title}>Your inventory, in focus.</Text><Text style={s.muted}>Sign in to view live business data and demand forecasts.</Text><Card><Field label="Email" value={email} onChangeText={setEmail} /><Field label="Password" value={password} onChangeText={setPassword} secure /><ErrorText text={error} /><Button title={busy ? 'Signing in…' : 'Sign in'} onPress={submit} disabled={busy} /></Card><Text style={s.note}>Use the same account as the StockGuard website.</Text></ScrollView></KeyboardAvoidingView>;
}

function Home({ currency }: { currency: string }) {
  const [data, setData] = useState<Overview | null>(null), [error, setError] = useState('');
  const load = useCallback(async () => { try { setData(await api<Overview>('/analytics/overview?days=30')); setError(''); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  return <Page title="Overview" subtitle="Last 30 days of recorded sales"><ErrorText text={error} />{!data && !error ? <ActivityIndicator color={c.cyan} /> : null}{data ? <><View style={s.grid}>{([['Revenue', money(data.totals.revenue, currency)], ['Units sold', number(data.totals.units)], ['Sale records', number(data.totals.saleRecords)], ['Low stock', number(data.totals.lowStockLocations)]] as const).map(([label, value]) => <View key={label} style={s.metricCard}><Text style={s.muted}>{label}</Text><Text style={s.metric}>{value}</Text></View>)}</View><Card><Text style={s.cardTitle}>Recent sales trend</Text>{data.daily.length ? <View style={s.chart}>{data.daily.slice(-12).map((day, _, list) => <View key={day.date} style={[s.bar, { height: 12 + (day.revenue / Math.max(...list.map(item => item.revenue), 1)) * 80 }]} />)}</View> : <Text style={s.muted}>Upload sales data to see a trend.</Text>}<Text style={s.note}>{data.period.startDate || 'No sales'} – {data.period.endDate || 'No sales'}</Text></Card><Card><Text style={s.cardTitle}>Top products</Text>{data.productSales.slice(0, 4).map(item => <View style={s.row} key={item.productId}><View style={{ flex: 1 }}><Text style={s.strong}>{item.name}</Text><Text style={s.muted}>{item.sku} · {number(item.units)} units</Text></View><Text style={s.strong}>{money(item.revenue, currency)}</Text></View>)}{!data.productSales.length ? <Text style={s.muted}>No sales yet.</Text> : null}</Card><Card><Text style={s.cardTitle}>Latest forecast</Text>{data.latestForecast ? <><Text style={s.strong}>{data.latestForecast.productName}</Text><Text style={s.muted}>{data.latestForecast.horizonDays} days · {data.latestForecast.model}</Text><Text style={s.accent}>{number(data.latestForecast.forecastTotal)} predicted units</Text></> : <Text style={s.muted}>Run a forecast after importing sales data.</Text>}</Card></> : null}<Button title="Refresh overview" onPress={() => void load()} secondary /></Page>;
}

function Products({ currency, canWrite }: { currency: string; canWrite: boolean }) {
  const [products, setProducts] = useState<Product[]>([]), [search, setSearch] = useState(''), [error, setError] = useState('');
  const [editing, setEditing] = useState<Product | null>(null), [showForm, setShowForm] = useState(false), [busy, setBusy] = useState(false);
  const [name, setName] = useState(''), [sku, setSku] = useState(''), [category, setCategory] = useState(''), [supplier, setSupplier] = useState('');
  const [stock, setStock] = useState('0'), [reorder, setReorder] = useState('0'), [price, setPrice] = useState('0');
  const load = useCallback(async () => { try { setProducts((await api<{ products: Product[] }>('/products')).products); setError(''); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  function reset() { setEditing(null); setShowForm(false); setName(''); setSku(''); setCategory(''); setSupplier(''); setStock('0'); setReorder('0'); setPrice('0'); }
  function begin(product?: Product) { setEditing(product || null); setShowForm(true); setName(product?.name || ''); setSku(product?.sku || ''); setCategory(product?.category || ''); setSupplier(product?.supplier || ''); setStock(String(product?.stock ?? 0)); setReorder(String(product?.reorder ?? 0)); setPrice(String(product?.price ?? 0)); }
  async function save() { if (!name.trim() || !sku.trim()) return setError('Name and SKU are required.'); setBusy(true); setError(''); try { const payload = { name, sku, category, supplier, stock: Number(stock), reorder: Number(reorder), price: Number(price) }; await api(editing ? `/products/${editing.id}` : '/products', jsonBody(payload, editing ? 'PATCH' : 'POST')); reset(); await load(); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  function remove(product: Product) { Alert.alert('Delete product?', `${product.name} will be removed from active inventory.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await api(`/products/${product.id}`, { method: 'DELETE' }); if (editing?.id === product.id) reset(); await load(); } catch (cause) { setError(message(cause)); } } }]); }
  const visible = products.filter(product => `${product.name} ${product.sku} ${product.category}`.toLowerCase().includes(search.toLowerCase()));
  return <Page title="Products" subtitle={`${products.length} items in your business`}><TextInput accessibilityLabel="Search products" style={s.input} placeholder="Search products or SKU" placeholderTextColor={c.muted} value={search} onChangeText={setSearch} />{canWrite ? <Button title={showForm ? 'Cancel editing' : '+ Add product'} onPress={() => showForm ? reset() : begin()} secondary={showForm} /> : null}{showForm ? <Card><Text style={s.cardTitle}>{editing ? 'Edit product' : 'New product'}</Text><Field label="Name" value={name} onChangeText={setName} /><Field label="SKU" value={sku} onChangeText={setSku} /><Field label="Category" value={category} onChangeText={setCategory} /><Field label="Supplier" value={supplier} onChangeText={setSupplier} /><Field label="Stock" value={stock} onChangeText={setStock} numeric /><Field label="Reorder point" value={reorder} onChangeText={setReorder} numeric /><Field label="Price" value={price} onChangeText={setPrice} numeric /><Button title={busy ? 'Saving…' : editing ? 'Update product' : 'Save product'} onPress={save} disabled={busy} /></Card> : null}<ErrorText text={error} />{visible.map(product => { const low = product.reorder > 0 && product.stock < product.reorder; return <Card key={product.id}><View style={s.row}><View style={{ flex: 1 }}><Text style={s.strong}>{product.name}</Text><Text style={s.muted}>{product.sku} · {product.category || 'Uncategorized'}</Text></View><Text style={[s.badge, low && { color: c.amber }]}>{low ? 'LOW' : 'OK'}</Text></View><View style={s.row}><Text style={s.muted}>Stock {number(product.stock)} · reorder {number(product.reorder)}</Text><Text style={s.strong}>{money(product.price, currency)}</Text></View>{canWrite ? <View style={s.actionRow}><Button title="Edit" onPress={() => begin(product)} secondary compact /><Button title="Delete" onPress={() => remove(product)} danger compact /></View> : null}</Card>; })}{!visible.length ? <Text style={s.muted}>No matching products.</Text> : null}<Button title="Refresh products" onPress={() => void load()} secondary /></Page>;
}

function Forecast({ canWrite }: { canWrite: boolean }) {
  const [series, setSeries] = useState<Series[]>([]), [selected, setSelected] = useState<Series | null>(null), [run, setRun] = useState<ForecastRun | null>(null);
  const [horizon, setHorizon] = useState<7 | 14 | 28>(28), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async () => { try { const [available, latest] = await Promise.all([api<{ series: Series[] }>('/forecasts/series'), api<{ run: ForecastRun | null }>('/forecasts/latest')]); setSeries(available.series); setSelected(current => current || available.series[0] || null); setRun(latest.run); setError(''); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function generate() { if (!selected) return; setBusy(true); setError(''); try { setRun((await api<{ run: ForecastRun }>('/forecasts/run', jsonBody({ storeId: selected.storeId, productId: selected.productId, horizon }))).run); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <Page title="AI forecast" subtitle="Demand from your uploaded sales history"><Card><Text style={s.cardTitle}>Sales series</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{series.map(item => <Pressable key={`${item.storeId}-${item.productId}`} onPress={() => setSelected(item)} style={[s.chip, selected?.storeId === item.storeId && selected.productId === item.productId && s.chipActive]}><Text style={s.strong}>{item.productName} · {item.storeCode}</Text></Pressable>)}</ScrollView>{!series.length ? <Text style={s.muted}>Upload a sales CSV to enable forecasting.</Text> : null}{selected ? <Text style={s.muted}>{number(selected.observations)} records · latest {selected.latestActualDate}</Text> : null}<Text style={s.label}>Horizon</Text><Chips values={[7, 14, 28] as const} selected={horizon} onSelect={setHorizon} format={value => `${value} days`} />{canWrite ? <Button title={busy ? 'Training & comparing…' : 'Run live comparison'} onPress={generate} disabled={busy || !selected} /> : null}</Card><ErrorText text={error} />{run ? <><Card><Text style={s.cardTitle}>{run.productName}</Text><Text style={s.muted}>{run.sku} · {run.storeCode}</Text><Text style={s.big}>{number(run.forecastTotal)}</Text><Text style={s.muted}>Predicted units over {run.horizon} days</Text><Text style={s.muted}>Selected: {run.model.replaceAll('_', ' ')} v{run.modelVersion}</Text><Text style={s.muted}>Backtest MAE {run.backtest.mae.toFixed(2)} · RMSE {run.backtest.rmse.toFixed(2)}</Text>{run.modelSelection ? <Text style={s.note}>{run.modelSelection}</Text> : null}</Card><Card><Text style={s.cardTitle}>Live model comparison</Text>{run.comparisons?.map(item => <View style={s.row} key={`${item.model}:${item.modelVersion}`}><View><Text style={s.strong}>{item.model.replaceAll('_', ' ')}{item.selected ? ' · selected' : ''}</Text><Text style={s.muted}>MAE {item.mae.toFixed(3)} · RMSE {item.rmse.toFixed(3)}</Text></View></View>)}</Card><Card><Text style={s.cardTitle}>Daily predictions</Text>{run.predictions.map(point => <View style={s.row} key={point.date}><Text style={s.muted}>{point.date}</Text><Text style={s.strong}>{point.forecast_sales.toFixed(2)} units</Text></View>)}</Card></> : <Text style={s.muted}>No saved forecast yet.</Text>}</Page>;
}

function Upload({ canWrite }: { canWrite: boolean }) {
  const [history, setHistory] = useState<ImportRecord[]>([]), [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setHistory((await api<{ imports: ImportRecord[] }>('/imports')).imports); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function choose() { setError(''); setSuccess(''); try { const picked = await DocumentPicker.getDocumentAsync({ type: '*/*', copyToCacheDirectory: true }); if (picked.canceled) return; const file = picked.assets[0]; if (!file.name.toLowerCase().endsWith('.csv')) return setError('Choose a .csv file.'); if ((file.size || 0) > 2 * 1024 * 1024) return setError('CSV file must be 2 MB or smaller.'); setBusy(true); const form = new FormData(); form.append('file', { uri: file.uri, name: file.name, type: 'text/csv' } as unknown as Blob); const result = await api<{ import: ImportRecord }>('/imports/sales', { method: 'POST', body: form }); setSuccess(`${result.import.records} records imported.`); await load(); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <Page title="CSV upload" subtitle="Bring your sales history into StockGuard"><Card><Text style={s.cardTitle}>Sales data file</Text><Text style={s.muted}>Select a CSV up to 2 MB. The server validates it before import.</Text>{canWrite ? <Button title={busy ? 'Uploading…' : 'Choose CSV file'} onPress={choose} disabled={busy} /> : <Text style={s.muted}>Your role cannot upload files.</Text>}<ErrorText text={error} />{success ? <Text style={s.accent}>{success}</Text> : null}</Card><Card><Text style={s.cardTitle}>Required columns</Text><Text style={s.code}>date, sku, product_name, category, quantity_sold, revenue</Text><Text style={s.note}>Optional: store_id. Dates use YYYY-MM-DD.</Text></Card><Text style={s.cardTitle}>Recent uploads</Text>{history.map(item => <Card key={item.id}><Text style={s.strong}>{item.name}</Text><Text style={s.muted}>{number(item.records)} records · {item.status} · {item.date.slice(0, 10)}</Text></Card>)}{!history.length ? <Text style={s.muted}>No uploads yet.</Text> : null}</Page>;
}

function Reports({ back, canWrite }: { back: () => void; canWrite: boolean }) {
  const [reports, setReports] = useState<ReportRecord[]>([]), [type, setType] = useState<'sales' | 'inventory' | 'forecast'>('sales'), [days, setDays] = useState<typeof periods[number]>(180), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async () => { try { setReports((await api<{ reports: ReportRecord[] }>('/reports')).reports); setError(''); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function shareReport(content: string, report: ReportRecord) { await Share.share({ title: report.name, message: `${report.filename}\n\n${content}` }); }
  async function generate() { setBusy(true); setError(''); try { const result = await api<{ report: ReportRecord; content: string }>('/reports', jsonBody({ type, days })); await load(); await shareReport(result.content, result.report); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  async function open(report: ReportRecord) { try { const result = await api<{ report: ReportRecord; content: string }>(`/reports/${report.id}`); await shareReport(result.content, result.report); } catch (cause) { setError(message(cause)); } }
  return <Page title="Reports" subtitle="Generate and share live business reports" back={back}><Card><Text style={s.cardTitle}>New report</Text><Text style={s.label}>Report type</Text><Chips values={['sales', 'inventory', 'forecast'] as const} selected={type} onSelect={setType} format={value => value[0].toUpperCase() + value.slice(1)} />{type !== 'forecast' ? <><Text style={s.label}>Reporting period</Text><Chips values={periods} selected={days} onSelect={setDays} format={value => `${value} days`} /></> : null}{canWrite ? <Button title={busy ? 'Generating…' : 'Generate & share'} onPress={generate} disabled={busy} /> : <Text style={s.muted}>Your role can open saved reports but cannot generate new ones.</Text>}</Card><ErrorText text={error} /><Card><Text style={s.cardTitle}>Saved reports</Text><Text style={s.muted}>{reports.length} report snapshots · {number(reports.reduce((sum, item) => sum + item.sizeBytes, 0))} bytes</Text></Card>{reports.map(report => <Card key={report.id}><View style={s.row}><View style={{ flex: 1 }}><Text style={s.strong}>{report.name}</Text><Text style={s.muted}>{report.format.toUpperCase()} · {number(report.sizeBytes)} bytes · {report.createdAt.slice(0, 10)}</Text></View><Button title="Share" onPress={() => void open(report)} compact secondary /></View></Card>)}{!reports.length ? <Text style={s.muted}>No reports generated yet.</Text> : null}</Page>;
}

function Insights({ currency, back }: { currency: string; back: () => void }) {
  const [days, setDays] = useState<typeof periods[number]>(180), [data, setData] = useState<Overview | null>(null), [error, setError] = useState('');
  const load = useCallback(async () => { try { setData(await api<Overview>(`/analytics/overview?days=${days}`)); setError(''); } catch (cause) { setError(message(cause)); } }, [days]);
  useEffect(() => { void load(); }, [load]);
  const top = data?.productSales[0], category = data?.categories[0], low = data?.inventory.filter(item => item.lowStock) || [];
  return <Page title="Business insights" subtitle="Live signals from sales, inventory and forecasts" back={back}><Chips values={periods} selected={days} onSelect={setDays} format={value => `${value}d`} /><ErrorText text={error} />{!data && !error ? <ActivityIndicator color={c.cyan} /> : null}{data ? <><View style={s.grid}><View style={s.metricCard}><Text style={s.muted}>Revenue</Text><Text style={s.metric}>{money(data.totals.revenue, currency)}</Text></View><View style={s.metricCard}><Text style={s.muted}>Low stock</Text><Text style={[s.metric, low.length ? { color: c.amber } : null]}>{low.length}</Text></View></View><Card><Text style={s.signal}>GROWTH SIGNAL</Text><Text style={s.cardTitle}>{top ? `${top.name} leads product revenue` : 'Sales history needed'}</Text><Text style={s.muted}>{top ? `${money(top.revenue, currency)} revenue from ${number(top.units)} units.` : 'Upload sales data to create insights.'}</Text></Card><Card><Text style={[s.signal, { color: c.amber }]}>ACTION REQUIRED</Text><Text style={s.cardTitle}>{low.length ? `${low.length} inventory locations need attention` : 'Inventory is above reorder levels'}</Text>{low.slice(0, 5).map(item => <View key={`${item.productId}-${item.store}`} style={s.row}><View><Text style={s.strong}>{item.name}</Text><Text style={s.muted}>{item.store} · stock {item.stock}</Text></View><Text style={{ color: c.amber }}>Reorder {item.reorderPoint}</Text></View>)}</Card><Card><Text style={s.signal}>CATEGORY OPPORTUNITY</Text><Text style={s.cardTitle}>{category?.name || 'No category data'}</Text><Text style={s.muted}>{category ? `${money(category.revenue, currency)} revenue and ${number(category.units)} units.` : 'Categorized sales will appear here.'}</Text></Card><Card><Text style={s.cardTitle}>Top products</Text>{data.productSales.slice(0, 8).map((item, index) => <View key={item.productId} style={s.row}><Text style={s.strong}>{index + 1}. {item.name}</Text><Text style={s.muted}>{money(item.revenue, currency)}</Text></View>)}</Card><Card><Text style={s.cardTitle}>Revenue trend</Text>{data.daily.length ? <View style={s.chart}>{data.daily.slice(-16).map((day, _, list) => <View key={day.date} style={[s.bar, { height: 10 + day.revenue / Math.max(...list.map(item => item.revenue), 1) * 88 }]} />)}</View> : <Text style={s.muted}>No trend available.</Text>}</Card><Card><Text style={s.cardTitle}>Forecast signal</Text>{data.latestForecast ? <><Text style={s.strong}>{data.latestForecast.productName}</Text><Text style={s.muted}>{number(data.latestForecast.forecastTotal)} units · {data.latestForecast.horizonDays} days · {data.latestForecast.model}</Text></> : <Text style={s.muted}>Run a forecast to add forward-looking insight.</Text>}</Card></> : null}</Page>;
}

function Profile({ user, onUserChange, back }: { user: User; onUserChange: (user: User) => void; back: () => void }) {
  const manager = ['owner', 'admin'].includes(user.role), [name, setName] = useState(user.name), [businessName, setBusinessName] = useState(user.business?.name || ''), [timezone, setTimezone] = useState(user.business?.timezone || 'Asia/Karachi'), [currency, setCurrency] = useState(user.business?.currency || 'PKR'), [busy, setBusy] = useState(false), [error, setError] = useState(''), [saved, setSaved] = useState('');
  async function save() { setBusy(true); setError(''); setSaved(''); try { const body = manager ? { name, businessName, timezone, currency } : { name }; const result = await api<{ user: User }>('/auth/me', jsonBody(body, 'PATCH')); onUserChange(result.user); setSaved('Profile updated.'); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <Page title="My profile" subtitle="Manage your StockGuard account" back={back}><Card><Text style={s.profileAvatar}>{user.name.slice(0, 2).toUpperCase()}</Text><Text style={s.cardTitle}>{user.name}</Text><Text style={s.muted}>{user.email}</Text><Text style={s.badge}>{user.role.toUpperCase()}</Text></Card><Card><Field label="Full name" value={name} onChangeText={setName} /><Text style={s.label}>Email address</Text><Text style={s.readonly}>{user.email}</Text>{manager ? <><Field label="Business name" value={businessName} onChangeText={setBusinessName} /><Field label="Timezone" value={timezone} onChangeText={setTimezone} /><Field label="Currency" value={currency} onChangeText={setCurrency} /></> : null}<ErrorText text={error} />{saved ? <Text style={s.accent}>{saved}</Text> : null}<Button title={busy ? 'Saving…' : 'Save profile'} onPress={save} disabled={busy} /></Card></Page>;
}

function useSettings() {
  const [settings, setSettings] = useState<SettingsData | null>(null), [error, setError] = useState('');
  const load = useCallback(async () => { try { setSettings((await api<{ settings: SettingsData }>('/settings')).settings); setError(''); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  return { settings, setSettings, error, setError };
}

function Settings({ user, back, notifications }: { user: User; back: () => void; notifications: () => void }) {
  const { settings, setSettings, error, setError } = useSettings(), [busy, setBusy] = useState(false), [saved, setSaved] = useState('');
  const manager = ['owner', 'admin'].includes(user.role);
  async function save() { if (!settings) return; setBusy(true); setError(''); setSaved(''); try { const body = { theme: settings.theme, ...(manager ? settings.business : {}) }; const result = await api<{ settings: SettingsData }>('/settings', jsonBody(body, 'PATCH')); setSettings(result.settings); setSaved('Settings saved.'); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <Page title="Settings" subtitle="Business defaults and app preferences" back={back}>{!settings && !error ? <ActivityIndicator color={c.cyan} /> : null}<ErrorText text={error} />{settings ? <><Card><Text style={s.cardTitle}>Notifications</Text><Text style={s.muted}>Choose which stock, forecast and security events you receive.</Text><Button title="Manage notifications" onPress={notifications} secondary /></Card><Card><Text style={s.cardTitle}>Appearance</Text><Text style={s.label}>Theme</Text><Chips values={['dark', 'system'] as const} selected={settings.theme} onSelect={theme => setSettings({ ...settings, theme })} format={value => value === 'dark' ? 'Dark' : 'Use device'} /></Card><Card><Text style={s.cardTitle}>AI models</Text><Text style={s.strong}>Production: Global XGBoost + seasonal fallback</Text><Text style={s.muted}>Live comparisons: Linear Regression, ARIMA and Random Forest. The lowest backtest MAE is selected for each business forecast.</Text></Card><Card><Text style={s.cardTitle}>Security</Text><Text style={s.strong}>Encrypted mobile session</Text><Text style={s.muted}>Refresh credentials stay in the device secure store. API access is protected by role-based authorization.</Text></Card><Card><Text style={s.cardTitle}>Inventory & forecast defaults</Text>{manager ? <><Field label="Safety stock percent" value={String(settings.business.safetyStockPercent)} numeric onChangeText={value => setSettings({ ...settings, business: { ...settings.business, safetyStockPercent: Number(value) } })} /><Field label="Default lead time days" value={String(settings.business.defaultLeadTimeDays)} numeric onChangeText={value => setSettings({ ...settings, business: { ...settings.business, defaultLeadTimeDays: Number(value) } })} /><Text style={s.label}>Default forecast horizon</Text><Chips values={[7, 14, 28] as const} selected={settings.business.forecastHorizonDays} onSelect={value => setSettings({ ...settings, business: { ...settings.business, forecastHorizonDays: value } })} format={value => `${value} days`} /></> : <Text style={s.muted}>Only owners and administrators can change business defaults.</Text>}</Card>{saved ? <Text style={s.accent}>{saved}</Text> : null}<Button title={busy ? 'Saving…' : 'Save settings'} onPress={save} disabled={busy} /></> : null}</Page>;
}

const notificationLabels: Record<keyof NotificationSettings, [string, string]> = { lowStock: ['Low stock alerts', 'Notify when inventory falls below its reorder point.'], forecastReady: ['Forecast ready', 'Notify when an AI forecast finishes.'], weeklySummary: ['Weekly summary', 'Receive a weekly business performance digest.'], demandSpike: ['Demand spike alerts', 'Notify when forecast demand rises sharply.'], newLogin: ['New login detection', 'Alert when a new device signs in.'], email: ['Email notifications', 'Send enabled notifications by email.'] };
function Notifications({ back }: { back: () => void }) {
  const { settings, setSettings, error, setError } = useSettings(), [busy, setBusy] = useState(false), [saved, setSaved] = useState('');
  async function save() { if (!settings) return; setBusy(true); setError(''); setSaved(''); try { const result = await api<{ settings: SettingsData }>('/settings', jsonBody({ notifications: settings.notifications }, 'PATCH')); setSettings(result.settings); setSaved('Notification preferences saved.'); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  return <Page title="Notifications" subtitle="Control the alerts you receive" back={back}>{!settings && !error ? <ActivityIndicator color={c.cyan} /> : null}<ErrorText text={error} />{settings ? <Card>{(Object.keys(notificationLabels) as (keyof NotificationSettings)[]).map(key => <View key={key} style={s.settingRow}><View style={{ flex: 1 }}><Text style={s.strong}>{notificationLabels[key][0]}</Text><Text style={s.muted}>{notificationLabels[key][1]}</Text></View><Switch value={settings.notifications[key]} onValueChange={value => setSettings({ ...settings, notifications: { ...settings.notifications, [key]: value } })} trackColor={{ false: c.line, true: c.blue }} thumbColor="white" /></View>)}</Card> : null}{saved ? <Text style={s.accent}>{saved}</Text> : null}<Button title={busy ? 'Saving…' : 'Save notifications'} onPress={save} disabled={busy || !settings} /></Page>;
}

function Admin({ currentUser, back }: { currentUser: User; back: () => void }) {
  const [users, setUsers] = useState<AdminUser[]>([]), [showAdd, setShowAdd] = useState(false), [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [role, setRole] = useState<'admin' | 'manager' | 'analyst' | 'staff'>('staff'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const load = useCallback(async () => { try { setUsers((await api<{ users: AdminUser[] }>('/admin/users')).users); setError(''); } catch (cause) { setError(message(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function add() { setBusy(true); setError(''); try { await api('/admin/users', jsonBody({ name, email, password, role })); setName(''); setEmail(''); setPassword(''); setShowAdd(false); await load(); } catch (cause) { setError(message(cause)); } finally { setBusy(false); } }
  async function update(id: string, value: { role?: string; status?: string }) { setError(''); try { await api(`/admin/users/${id}`, jsonBody(value, 'PATCH')); await load(); } catch (cause) { setError(message(cause)); } }
  return <Page title="User management" subtitle={`${users.length} workspace users`} back={back}><Button title={showAdd ? 'Cancel' : '+ Add user'} onPress={() => setShowAdd(!showAdd)} secondary={showAdd} />{showAdd ? <Card><Text style={s.cardTitle}>Create account</Text><Field label="Full name" value={name} onChangeText={setName} /><Field label="Email" value={email} onChangeText={setEmail} /><Field label="Temporary password" value={password} onChangeText={setPassword} secure /><Text style={s.label}>Role</Text><Chips values={['admin', 'manager', 'analyst', 'staff'] as const} selected={role} onSelect={setRole} /><Button title={busy ? 'Creating…' : 'Create user'} onPress={add} disabled={busy || !name || !email || password.length < 8} /></Card> : null}<ErrorText text={error} />{users.map(user => <Card key={user.id}><View style={s.row}><View style={{ flex: 1 }}><Text style={s.strong}>{user.name}{user.id === currentUser.id ? ' · You' : ''}</Text><Text style={s.muted}>{user.email}</Text></View><Text style={[s.badge, user.status !== 'active' && { color: c.red }]}>{user.status.toUpperCase()}</Text></View><Text style={s.muted}>Role: {user.role} · last login {user.lastLoginAt ? user.lastLoginAt.slice(0, 10) : 'never'}</Text>{user.role !== 'owner' ? <><Chips values={['admin', 'manager', 'analyst', 'staff'] as const} selected={user.role as 'admin' | 'manager' | 'analyst' | 'staff'} onSelect={next => void update(user.id, { role: next })} /><Button title={user.status === 'active' ? 'Disable account' : 'Enable account'} onPress={() => void update(user.id, { status: user.status === 'active' ? 'disabled' : 'active' })} secondary={user.status !== 'active'} danger={user.status === 'active'} compact /></> : null}</Card>)}</Page>;
}

function More({ user, navigate, onLogout }: { user: User; navigate: (screen: Screen) => void; onLogout: () => void }) {
  const [busy, setBusy] = useState(false);
  async function signOut() { setBusy(true); await logout(); onLogout(); setBusy(false); }
  const entries: [Screen, string, string][] = [['Reports', 'Reports', 'Generate and share sales, inventory and forecast exports.'], ['Insights', 'Business insights', 'See growth signals, risks and product performance.'], ['Profile', 'Profile', 'Edit your name and business information.'], ['Settings', 'Settings', 'Set inventory, forecast and appearance defaults.'], ['Notifications', 'Notifications', 'Choose which operational alerts you receive.']];
  if (['owner', 'admin'].includes(user.role)) entries.push(['Admin', 'Admin & users', 'Create accounts and manage roles and access.']);
  return <Page title="More" subtitle="Account, reports and workspace controls"><Card><Text style={s.profileAvatar}>{user.name.slice(0, 2).toUpperCase()}</Text><Text style={s.cardTitle}>{user.name}</Text><Text style={s.muted}>{user.email} · {user.role}</Text></Card>{entries.map(([screen, title, detail]) => <Pressable key={screen} onPress={() => navigate(screen)} style={s.menuCard}><View style={{ flex: 1 }}><Text style={s.cardTitle}>{title}</Text><Text style={s.muted}>{detail}</Text></View><Text style={s.chevron}>›</Text></Pressable>)}<Button title={busy ? 'Signing out…' : 'Sign out'} onPress={signOut} disabled={busy} danger /></Page>;
}

function Main({ user, onUserChange, onLogout }: { user: User; onUserChange: (user: User) => void; onLogout: () => void }) {
  const [screen, setScreen] = useState<Screen>('Home'), canWrite = ['owner', 'admin', 'analyst'].includes(user.role), currency = user.business?.currency || 'PKR', back = () => setScreen('More');
  let content: React.ReactNode;
  if (screen === 'Home') content = <Home currency={currency} />; else if (screen === 'Products') content = <Products currency={currency} canWrite={canWrite} />; else if (screen === 'Forecast') content = <Forecast canWrite={canWrite} />; else if (screen === 'Upload') content = <Upload canWrite={canWrite} />; else if (screen === 'Reports') content = <Reports back={back} canWrite={canWrite} />; else if (screen === 'Insights') content = <Insights currency={currency} back={back} />; else if (screen === 'Profile') content = <Profile user={user} onUserChange={onUserChange} back={back} />; else if (screen === 'Settings') content = <Settings user={user} back={back} notifications={() => setScreen('Notifications')} />; else if (screen === 'Notifications') content = <Notifications back={back} />; else if (screen === 'Admin') content = <Admin currentUser={user} back={back} />; else content = <More user={user} navigate={setScreen} onLogout={onLogout} />;
  const activeTab: Tab = tabs.includes(screen as Tab) ? screen as Tab : 'More';
  return <View style={{ flex: 1 }}><View style={s.header}><View><Text style={s.brand}>StockGuard <Text style={{ color: c.cyan }}>AI</Text></Text><Text style={s.note}>{user.business?.name || 'Workspace'}</Text></View><Pressable onPress={() => setScreen('Profile')}><Text style={s.avatar}>{user.name.slice(0, 1).toUpperCase()}</Text></Pressable></View><View style={{ flex: 1 }}>{content}</View><View style={s.tabs}>{tabs.map(item => <Pressable key={item} accessibilityRole="tab" accessibilityState={{ selected: item === activeTab }} onPress={() => setScreen(item)} style={s.tab}><Text style={[s.tabText, item === activeTab && { color: c.cyan }]}>{item}</Text></Pressable>)}</View></View>;
}

export default function App() {
  const [user, setUser] = useState<User | null>(null), [starting, setStarting] = useState(true), [error, setError] = useState('');
  const start = useCallback(async () => { setStarting(true); setError(''); try { setUser(await restoreSession()); } catch (cause) { setError(`Connection error: ${message(cause)}`); } finally { setStarting(false); } }, []);
  useEffect(() => { void start(); }, [start]);
  return <SafeAreaProvider><SafeAreaView style={{ flex: 1, backgroundColor: c.bg }} edges={['top', 'bottom']}><StatusBar style="light" />{starting ? <ActivityIndicator style={{ flex: 1 }} color={c.cyan} /> : user ? <Main user={user} onUserChange={setUser} onLogout={() => setUser(null)} /> : <Login onLogin={setUser} />}{error ? <View style={{ padding: 12 }}><ErrorText text={error} /><Button title="Retry connection" onPress={() => void start()} secondary /></View> : null}</SafeAreaView></SafeAreaProvider>;
}

const s = StyleSheet.create({
  content: { padding: 20, paddingBottom: 36, gap: 14 }, login: { flexGrow: 1, padding: 24, justifyContent: 'center', gap: 14 }, logo: { width: 210, height: 210, alignSelf: 'center' }, title: { color: c.text, fontSize: 25, fontWeight: '800' }, muted: { color: c.muted, fontSize: 12, lineHeight: 18 }, note: { color: c.muted, fontSize: 11, lineHeight: 17 }, back: { color: c.cyan, fontWeight: '700', fontSize: 14 },
  card: { backgroundColor: c.card, borderRadius: 18, borderWidth: 1, borderColor: c.line, padding: 16, gap: 10 }, cardTitle: { color: c.text, fontWeight: '700', fontSize: 16 }, menuCard: { backgroundColor: c.card, borderRadius: 16, borderWidth: 1, borderColor: c.line, padding: 16, flexDirection: 'row', alignItems: 'center', gap: 10 }, chevron: { color: c.cyan, fontSize: 30 }, grid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 }, metricCard: { width: '48%', backgroundColor: c.card, padding: 15, borderRadius: 16, borderWidth: 1, borderColor: c.line }, metric: { color: c.text, fontSize: 19, fontWeight: '800', marginTop: 5 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8, paddingVertical: 5 }, actionRow: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' }, settingRow: { flexDirection: 'row', gap: 12, alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: c.line }, strong: { color: c.text, fontSize: 12, fontWeight: '700' }, accent: { color: c.cyan, fontSize: 14, fontWeight: '800' }, signal: { color: c.cyan, fontSize: 10, letterSpacing: 1, fontWeight: '900' }, big: { color: c.cyan, fontSize: 38, fontWeight: '800' }, chart: { height: 108, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 5 }, bar: { flex: 1, borderRadius: 5, backgroundColor: c.blue },
  button: { minHeight: 44, backgroundColor: c.blue, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14 }, compactButton: { minHeight: 36, paddingHorizontal: 12 }, secondary: { backgroundColor: c.raised, borderColor: c.line, borderWidth: 1 }, dangerButton: { backgroundColor: '#702c3b', borderColor: c.red, borderWidth: 1 }, buttonText: { color: 'white', fontWeight: '700', fontSize: 13 }, label: { color: '#b8c8e0', fontSize: 12, fontWeight: '600', marginTop: 5 }, input: { color: c.text, backgroundColor: c.raised, borderWidth: 1, borderColor: c.line, borderRadius: 12, minHeight: 44, paddingHorizontal: 12 }, readonly: { color: c.muted, backgroundColor: c.bg, borderRadius: 12, padding: 13 }, error: { color: c.red, fontSize: 12 },
  badge: { color: c.cyan, fontSize: 11, fontWeight: '800' }, chip: { backgroundColor: c.raised, borderWidth: 1, borderColor: c.line, borderRadius: 10, padding: 9, marginRight: 6 }, chipActive: { borderColor: c.blue, backgroundColor: '#18446b' }, code: { color: c.cyan, fontSize: 11, lineHeight: 18 }, profileAvatar: { color: 'white', backgroundColor: c.blue, overflow: 'hidden', borderRadius: 18, padding: 16, alignSelf: 'flex-start', fontWeight: '900', fontSize: 20 }, header: { paddingHorizontal: 20, paddingVertical: 12, borderBottomWidth: 1, borderColor: c.line, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, brand: { color: c.text, fontSize: 20, fontWeight: '800' }, avatar: { color: 'white', backgroundColor: c.blue, overflow: 'hidden', borderRadius: 12, padding: 10, fontWeight: '800' }, tabs: { flexDirection: 'row', backgroundColor: c.card, borderTopWidth: 1, borderColor: c.line, paddingVertical: 9 }, tab: { flex: 1, alignItems: 'center', paddingVertical: 8 }, tabText: { color: c.muted, fontSize: 10, fontWeight: '700' },
});
