import { useEffect, useState } from "react";
import { ArrowRight, Eye, EyeOff, LockKeyhole, ShieldCheck } from "lucide-react";

import { acceptInvitation, loadInvitation } from "./auth";

export default function InvitePage() {
  const token = decodeURIComponent(window.location.pathname.split("/").filter(Boolean).pop() || "");
  const [invitation,setInvitation]=useState(null),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[show,setShow]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{loadInvitation(token).then((data)=>setInvitation(data.invitation)).catch((cause)=>setError(cause.message)).finally(()=>setLoading(false));},[token]);
  async function submit(event){event.preventDefault();setError("");if(password!==confirm)return setError("Passwords do not match.");setLoading(true);try{await acceptInvitation(token,password);window.location.assign("/dashboard");}catch(cause){setError(cause.message);setLoading(false);}}
  return <div className="login-page"><section className="login-story"><a className="login-logo" href="/"><span><img src="/stockguard-logo.png" alt=""/></span><b>StockGuard <em>AI</em></b></a><div className="login-story-copy"><p className="kicker">Team invitation</p><h1>Join a secure inventory workspace.</h1><p>Your administrator assigned your role and permissions. Set a password to activate the account.</p><div className="login-proof"><ShieldCheck/><span><b>Protected access</b><small>Expiring invitation · role-based permissions</small></span></div></div><small>StockGuard AI · Predict today. Protect tomorrow.</small></section><section className="login-form-side"><form className="login-form" onSubmit={submit}><div className="login-lock"><LockKeyhole size={22}/></div><p className="kicker">Accept invitation</p>{loading&&!invitation?<><h2>Checking invitation…</h2><p>Please wait while StockGuard validates this secure link.</p></>:invitation?<><h2>Welcome, {invitation.name}</h2><p>Join <b>{invitation.businessName}</b> as <b>{invitation.role}</b>.</p><label>Email address<input readOnly value={invitation.email}/></label><label>Create password<div className="password-field"><input required minLength="8" autoComplete="new-password" type={show?"text":"password"} value={password} onChange={(event)=>setPassword(event.target.value)}/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></div></label><label>Confirm password<input required minLength="8" autoComplete="new-password" type={show?"text":"password"} value={confirm} onChange={(event)=>setConfirm(event.target.value)}/></label><button className="login-submit" type="submit" disabled={loading}>{loading?"Activating…":"Activate account"}{!loading&&<ArrowRight size={17}/>}</button></>:<><h2>Invitation unavailable</h2><p>Ask your StockGuard administrator to create a fresh invitation link.</p></>}{error&&<div className="form-error" role="alert">{error}</div>}</form></section></div>;
}
